// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyInstall(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyInstall'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function AssignModTag(arg1, arg2) {
  return window['go']['main']['App']['AssignModTag'](arg1, arg2);
}

export function CancelInstall(arg1) {
  return window['go']['main']['App']['CancelInstall'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckWhatsNew() {
  return window['go']['main']['App']['CheckWhatsNew']();
}

export function ClassificationType() {
  return window['go']['main']['App']['ClassificationType']();
}

export function ClassifyLibrary(arg1, arg2) {
  return window['go']['main']['App']['ClassifyLibrary'](arg1, arg2);
}

export function ConflictType() {
  return window['go']['main']['App']['ConflictType']();
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2, arg3);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DetectConflicts(arg1, arg2) {
  return window['go']['main']['App']['DetectConflicts'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function InstallFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallFromURL'](arg1, arg2, arg3);
}

export function LoadMetadata() {
  return window['go']['main']['App']['LoadMetadata']();
}

export function MoveFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3);
}

export function MoveMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveMod'](arg1, arg2, arg3);
}

export function PrepareInstall(arg1, arg2, arg3) {
  return window['go']['main']['App']['PrepareInstall'](arg1, arg2, arg3);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function RenameMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameMod'](arg1, arg2, arg3);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function RuntimeStatus() {
  return window['go']['main']['App']['RuntimeStatus']();
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function SelectFilesForInstall() {
  return window['go']['main']['App']['SelectFilesForInstall']();
}

export function SetAccentColor(arg1) {
  return window['go']['main']['App']['SetAccentColor'](arg1);
}

export function SetDefaultViewMode(arg1) {
  return window['go']['main']['App']['SetDefaultViewMode'](arg1);
}

export function SetModEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModEnabled'](arg1, arg2, arg3);
}

export function SetModPriority(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModPriority'](arg1, arg2, arg3);
}

export function SetModRoot(arg1) {
  return window['go']['main']['App']['SetModRoot'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function UnassignModTag(arg1, arg2) {
  return window['go']['main']['App']['UnassignModTag'](arg1, arg2);
}

export function UpdateType() {
  return window['go']['main']['App']['UpdateType']();
}
