// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';

export function RuntimeStatus():Promise<string>;

export function ScanLibrary(arg1:string):Promise<discovery.Library>;
