// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mutation} from '../models';
import {discovery} from '../models';

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<mutation.Result>;

export function DeleteMod(arg1:string,arg2:string,arg3:boolean):Promise<mutation.Result>;

export function MoveFolder(arg1:string,arg2:string,arg3:string):Promise<mutation.Result>;

export function MoveMod(arg1:string,arg2:string,arg3:string):Promise<mutation.Result>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<mutation.Result>;

export function RenameMod(arg1:string,arg2:string,arg3:string):Promise<mutation.Result>;

export function RuntimeStatus():Promise<string>;

export function ScanLibrary(arg1:string):Promise<discovery.Library>;

export function SetModEnabled(arg1:string,arg2:string,arg3:boolean):Promise<mutation.Result>;

export function SetModPriority(arg1:string,arg2:string,arg3:number):Promise<mutation.Result>;
