// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RuntimeStatus() {
  return window['go']['main']['App']['RuntimeStatus']();
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function SetModEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModEnabled'](arg1, arg2, arg3);
}
